# Generated by Django 3.2.6 on 2024-06-12 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240612_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Sin ciudad', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
