# Generated by Django 3.2.6 on 2024-09-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_streetpersonhistory_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetperson',
            name='common_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
