# Generated by Django 3.2.6 on 2024-10-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
